require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::ParticipantsController, :type => :controller do

  before do

    allow_any_instance_of(Admin::AdminApplicationController).to receive(:admin_signed_in?).and_return( true )
    allow_any_instance_of(ApplicationController).to receive(:current_user).and_return(
    {
      "login"=>"lagrangm", "studentId"=>35723, "email"=>"martin.lagrange@utt.fr", 
      "firstName"=>"Martin", "lastName"=>"LAGRANGE", "fullName"=>"Martin LAGRANGE", 
      "branch"=>"ISI", "level"=>"5", "speciality"=>"MPL", "surname"=>"TinMar", "jadis"=>"Arrière, arrière, arrière ... petit fils du célèbre Mathématicien Joseph-Louis Lagrange.", 
      "passions"=>"Théâtre & Impro (les Ch'UTT de vers !)\r\nInstruments de musique, Trompette\r\nSalsa Rueda de Casino\r\nDév web & Ruby\r\n[...]",
       "birthday"=>"1992-06-17T00:00:00+0200", "website"=>nil, "facebook"=>nil,
       "twitter"=>nil, "linkedin"=>nil, "viadeo"=>nil, "isStudent"=>true, "bdeMember"=>false, "_embed"=>{"badges"=>[32, 33, 1, 2, 11]}, "_links"=>[{"rel"=>"self",
        "uri"=>"/api/public/users/lagrangm"}, 
        {"rel"=>"user.badges", "uri"=>"/api/public/users/lagrangm/badges"},
        {"rel"=>"user.image", "uri"=>"/uploads/photos/lagrangm.png"}, {"rel"=>"user.official_image", "uri"=>"/uploads/photos/lagrangm_official.jpg"}]
    }
    )

  end


  WebMock.allow_net_connect!
  # This should return the minimal set of attributes required to create a valid
  # Participant. As you add validations to Participant, be sure to
  # adjust the attributes here as well.
  let(:game) { create(:game) }

  let(:valid_attributes) {
    {login: 'lagrangm', game_id: game.id, paid: false}
  }

  let(:invalid_attributes) {
    {login: nil, paid: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ParticipantsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all participants as @participants" do
      participant = Participant.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:participants)).to eq([participant])
    end
  end

  describe "GET show" do
    it "assigns the requested participant as @participant" do
      participant = Participant.create! valid_attributes
      get :show, {:id => participant.to_param}, valid_session
      expect(assigns(:participant)).to eq(participant)
    end
  end

  describe "GET new" do
    it "assigns a new participant as @participant" do
      get :new, {}, valid_session
      expect(assigns(:participant)).to be_a_new(Participant)
    end
  end

  describe "GET edit" do
    it "assigns the requested participant as @participant" do
      participant = Participant.create! valid_attributes
      get :edit, {:id => participant.to_param}, valid_session
      expect(assigns(:participant)).to eq(participant)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Participant" do
        expect {
          post :create, {:participant => valid_attributes}, valid_session
        }.to change(Participant, :count).by(1)
      end

      it "assigns a newly created participant as @participant" do
        post :create, {:participant => valid_attributes}, valid_session
        expect(assigns(:participant)).to be_a(Participant)
        expect(assigns(:participant)).to be_persisted
      end

      it "redirects to the created participant" do
        post :create, {:participant => valid_attributes}, valid_session
        expect(response).to redirect_to(Participant.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved participant as @participant" do
        post :create, {:participant => invalid_attributes}, valid_session
        expect(assigns(:participant)).to be_a_new(Participant)
      end

      it "re-renders the 'new' template" do
        post :create, {:participant => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        {paid: true}
      }

      it "updates the requested participant" do
        participant = Participant.create! valid_attributes
        put :update, {:id => participant.to_param, :participant => new_attributes}, valid_session
        participant.reload
        participant.paid == true
      end

      it "assigns the requested participant as @participant" do
        participant = Participant.create! valid_attributes
        put :update, {:id => participant.to_param, :participant => valid_attributes}, valid_session
        expect(assigns(:participant)).to eq(participant)
      end

      it "redirects to the participant" do
        participant = Participant.create! valid_attributes
        put :update, {:id => participant.to_param, :participant => valid_attributes}, valid_session
        expect(response).to redirect_to(participant)
      end
    end

    describe "with invalid params" do
      it "assigns the participant as @participant" do
        participant = Participant.create! valid_attributes
        put :update, {:id => participant.to_param, :participant => invalid_attributes}, valid_session
        expect(assigns(:participant)).to eq(participant)
      end

      it "re-renders the 'edit' template" do
        participant = Participant.create! valid_attributes
        put :update, {:id => participant.to_param, :participant => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested participant" do
      participant = Participant.create! valid_attributes
      expect {
        delete :destroy, {:id => participant.to_param}, valid_session
      }.to change(Participant, :count).by(-1)
    end

    it "redirects to the participants list" do
      participant = Participant.create! valid_attributes
      delete :destroy, {:id => participant.to_param}, valid_session
      expect(response).to redirect_to(participants_url)
    end
  end

end
